# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignerFile.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.swPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.swPages.setGeometry(QtCore.QRect(200, 40, 731, 591))
        self.swPages.setObjectName("swPages")
        self.pgConsent = QtWidgets.QWidget()
        self.pgConsent.setObjectName("pgConsent")
        self.chbAgree = QtWidgets.QCheckBox(self.pgConsent)
        self.chbAgree.setGeometry(QtCore.QRect(310, 430, 101, 21))
        self.chbAgree.setObjectName("chbAgree")
        self.lblTandC = QtWidgets.QLabel(self.pgConsent)
        self.lblTandC.setGeometry(QtCore.QRect(30, 90, 661, 241))
        self.lblTandC.setScaledContents(True)
        self.lblTandC.setWordWrap(True)
        self.lblTandC.setObjectName("lblTandC")
        self.lblError0 = QtWidgets.QLabel(self.pgConsent)
        self.lblError0.setGeometry(QtCore.QRect(200, 410, 301, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(174, 8, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 8, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblError0.setPalette(palette)
        self.lblError0.setObjectName("lblError0")
        self.lblConsent = QtWidgets.QLabel(self.pgConsent)
        self.lblConsent.setGeometry(QtCore.QRect(240, 40, 91, 31))
        self.lblConsent.setWordWrap(False)
        self.lblConsent.setObjectName("lblConsent")
        self.btnConfirm = QtWidgets.QPushButton(self.pgConsent)
        self.btnConfirm.setGeometry(QtCore.QRect(520, 450, 81, 32))
        self.btnConfirm.setObjectName("btnConfirm")
        self.swPages.addWidget(self.pgConsent)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.btnSubmit = QtWidgets.QPushButton(self.page)
        self.btnSubmit.setGeometry(QtCore.QRect(600, 450, 75, 23))
        self.btnSubmit.setObjectName("btnSubmit")
        self.lblDemographics = QtWidgets.QLabel(self.page)
        self.lblDemographics.setGeometry(QtCore.QRect(180, 60, 121, 16))
        self.lblDemographics.setObjectName("lblDemographics")
        self.wgForm = QtWidgets.QWidget(self.page)
        self.wgForm.setGeometry(QtCore.QRect(110, 110, 551, 201))
        self.wgForm.setObjectName("wgForm")
        self.lblErrorEmail = QtWidgets.QLabel(self.wgForm)
        self.lblErrorEmail.setGeometry(QtCore.QRect(280, 170, 251, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorEmail.setPalette(palette)
        self.lblErrorEmail.setObjectName("lblErrorEmail")
        self.lblPlease = QtWidgets.QLabel(self.wgForm)
        self.lblPlease.setGeometry(QtCore.QRect(0, 0, 251, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblPlease.setPalette(palette)
        self.lblPlease.setWordWrap(True)
        self.lblPlease.setObjectName("lblPlease")
        self.leEmail = QtWidgets.QLineEdit(self.wgForm)
        self.leEmail.setGeometry(QtCore.QRect(80, 170, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.leEmail.setFont(font)
        self.leEmail.setObjectName("leEmail")
        self.lblEmail = QtWidgets.QLabel(self.wgForm)
        self.lblEmail.setGeometry(QtCore.QRect(0, 170, 71, 21))
        self.lblEmail.setObjectName("lblEmail")
        self.cbEducation = QtWidgets.QComboBox(self.wgForm)
        self.cbEducation.setGeometry(QtCore.QRect(77, 140, 131, 22))
        self.cbEducation.setObjectName("cbEducation")
        self.cbEducation.addItem("")
        self.cbEducation.addItem("")
        self.cbEducation.addItem("")
        self.cbEducation.addItem("")
        self.cbEducation.addItem("")
        self.cbEducation.addItem("")
        self.cbEducation.addItem("")
        self.lblErrorGender = QtWidgets.QLabel(self.wgForm)
        self.lblErrorGender.setGeometry(QtCore.QRect(280, 110, 251, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorGender.setPalette(palette)
        self.lblErrorGender.setObjectName("lblErrorGender")
        self.lblAge = QtWidgets.QLabel(self.wgForm)
        self.lblAge.setGeometry(QtCore.QRect(0, 80, 47, 21))
        self.lblAge.setObjectName("lblAge")
        self.lblEducation = QtWidgets.QLabel(self.wgForm)
        self.lblEducation.setGeometry(QtCore.QRect(0, 140, 71, 21))
        self.lblEducation.setObjectName("lblEducation")
        self.leName = QtWidgets.QLineEdit(self.wgForm)
        self.leName.setGeometry(QtCore.QRect(80, 50, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.leName.setFont(font)
        self.leName.setObjectName("leName")
        self.wiGender = QtWidgets.QWidget(self.wgForm)
        self.wiGender.setGeometry(QtCore.QRect(80, 100, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.wiGender.setFont(font)
        self.wiGender.setObjectName("wiGender")
        self.rbtnWoman = QtWidgets.QRadioButton(self.wiGender)
        self.rbtnWoman.setGeometry(QtCore.QRect(0, 10, 82, 21))
        self.rbtnWoman.setObjectName("rbtnWoman")
        self.rbtnMan = QtWidgets.QRadioButton(self.wiGender)
        self.rbtnMan.setGeometry(QtCore.QRect(80, 10, 71, 21))
        self.rbtnMan.setObjectName("rbtnMan")
        self.rbtnOther = QtWidgets.QRadioButton(self.wiGender)
        self.rbtnOther.setGeometry(QtCore.QRect(140, 10, 71, 21))
        self.rbtnOther.setObjectName("rbtnOther")
        self.sbAge = QtWidgets.QSpinBox(self.wgForm)
        self.sbAge.setGeometry(QtCore.QRect(80, 80, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.sbAge.setFont(font)
        self.sbAge.setObjectName("sbAge")
        self.lblName = QtWidgets.QLabel(self.wgForm)
        self.lblName.setGeometry(QtCore.QRect(0, 50, 47, 21))
        self.lblName.setObjectName("lblName")
        self.lblErrorAge = QtWidgets.QLabel(self.wgForm)
        self.lblErrorAge.setGeometry(QtCore.QRect(280, 80, 251, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorAge.setPalette(palette)
        self.lblErrorAge.setObjectName("lblErrorAge")
        self.lblErrorEduc = QtWidgets.QLabel(self.wgForm)
        self.lblErrorEduc.setGeometry(QtCore.QRect(280, 140, 251, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorEduc.setPalette(palette)
        self.lblErrorEduc.setObjectName("lblErrorEduc")
        self.lblErrorName = QtWidgets.QLabel(self.wgForm)
        self.lblErrorName.setGeometry(QtCore.QRect(280, 50, 251, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorName.setPalette(palette)
        self.lblErrorName.setObjectName("lblErrorName")
        self.lblGender = QtWidgets.QLabel(self.wgForm)
        self.lblGender.setGeometry(QtCore.QRect(0, 110, 51, 21))
        self.lblGender.setObjectName("lblGender")
        self.swPages.addWidget(self.page)
        self.pgInstructions = QtWidgets.QWidget()
        self.pgInstructions.setObjectName("pgInstructions")
        self.lblInstructions = QtWidgets.QLabel(self.pgInstructions)
        self.lblInstructions.setGeometry(QtCore.QRect(250, 10, 81, 16))
        self.lblInstructions.setObjectName("lblInstructions")
        self.lblDescription = QtWidgets.QLabel(self.pgInstructions)
        self.lblDescription.setGeometry(QtCore.QRect(60, 50, 431, 151))
        self.lblDescription.setMouseTracking(True)
        self.lblDescription.setWordWrap(True)
        self.lblDescription.setObjectName("lblDescription")
        self.btnNext = QtWidgets.QPushButton(self.pgInstructions)
        self.btnNext.setGeometry(QtCore.QRect(400, 350, 113, 32))
        self.btnNext.setObjectName("btnNext")
        self.lblExample = QtWidgets.QLabel(self.pgInstructions)
        self.lblExample.setGeometry(QtCore.QRect(200, 180, 181, 161))
        self.lblExample.setText("")
        self.lblExample.setPixmap(QtGui.QPixmap("exampleFrame.png"))
        self.lblExample.setScaledContents(True)
        self.lblExample.setObjectName("lblExample")
        self.swPages.addWidget(self.pgInstructions)
        self.pgExperiment = QtWidgets.QWidget()
        self.pgExperiment.setObjectName("pgExperiment")
        self.lblBox = QtWidgets.QLabel(self.pgExperiment)
        self.lblBox.setGeometry(QtCore.QRect(70, 50, 471, 321))
        self.lblBox.setText("")
        self.lblBox.setPixmap(QtGui.QPixmap("blackbox.png"))
        self.lblBox.setScaledContents(True)
        self.lblBox.setObjectName("lblBox")
        self.lblFixPoint = QtWidgets.QLabel(self.pgExperiment)
        self.lblFixPoint.setGeometry(QtCore.QRect(280, 160, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblFixPoint.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblFixPoint.setFont(font)
        self.lblFixPoint.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFixPoint.setWordWrap(False)
        self.lblFixPoint.setObjectName("lblFixPoint")
        self.lblPractice2 = QtWidgets.QLabel(self.pgExperiment)
        self.lblPractice2.setGeometry(QtCore.QRect(320, 20, 161, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblPractice2.setPalette(palette)
        self.lblPractice2.setObjectName("lblPractice2")
        self.swPages.addWidget(self.pgExperiment)
        self.pgAnswer = QtWidgets.QWidget()
        self.pgAnswer.setObjectName("pgAnswer")
        self.lblQuestion = QtWidgets.QLabel(self.pgAnswer)
        self.lblQuestion.setGeometry(QtCore.QRect(130, 50, 341, 181))
        self.lblQuestion.setWordWrap(True)
        self.lblQuestion.setObjectName("lblQuestion")
        self.lblEntry1 = QtWidgets.QLabel(self.pgAnswer)
        self.lblEntry1.setGeometry(QtCore.QRect(80, 240, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblEntry1.setFont(font)
        self.lblEntry1.setObjectName("lblEntry1")
        self.lblEntry2 = QtWidgets.QLabel(self.pgAnswer)
        self.lblEntry2.setGeometry(QtCore.QRect(280, 240, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblEntry2.setFont(font)
        self.lblEntry2.setObjectName("lblEntry2")
        self.lblAnswer1 = QtWidgets.QLabel(self.pgAnswer)
        self.lblAnswer1.setGeometry(QtCore.QRect(80, 220, 60, 16))
        self.lblAnswer1.setObjectName("lblAnswer1")
        self.lblAnswer2 = QtWidgets.QLabel(self.pgAnswer)
        self.lblAnswer2.setGeometry(QtCore.QRect(280, 220, 60, 16))
        self.lblAnswer2.setObjectName("lblAnswer2")
        self.lblErrorDigit = QtWidgets.QLabel(self.pgAnswer)
        self.lblErrorDigit.setGeometry(QtCore.QRect(80, 200, 141, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 1, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 1, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorDigit.setPalette(palette)
        self.lblErrorDigit.setObjectName("lblErrorDigit")
        self.lblPractice = QtWidgets.QLabel(self.pgAnswer)
        self.lblPractice.setGeometry(QtCore.QRect(320, 40, 161, 16))
        self.lblPractice.setObjectName("lblPractice")
        self.swPages.addWidget(self.pgAnswer)
        self.pgEnd = QtWidgets.QWidget()
        self.pgEnd.setObjectName("pgEnd")
        self.lblDebrief = QtWidgets.QLabel(self.pgEnd)
        self.lblDebrief.setGeometry(QtCore.QRect(270, 40, 60, 16))
        self.lblDebrief.setObjectName("lblDebrief")
        self.lblThanks = QtWidgets.QLabel(self.pgEnd)
        self.lblThanks.setGeometry(QtCore.QRect(210, 150, 401, 171))
        self.lblThanks.setWordWrap(True)
        self.lblThanks.setObjectName("lblThanks")
        self.swPages.addWidget(self.pgEnd)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.swPages.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chbAgree.setText(_translate("MainWindow", "Yes, I agree"))
        self.lblTandC.setText(_translate("MainWindow", "<html><head/><body><p>Welcome to our study “Attentional Blink in Space and Time”!</p><p>This experiment has been adapted from a paradigm designed by Arni Kristjansson and Ken Nakayama from the University of Harvard and has been approved by the Research Ethics Committee. </p><p>Participation takes around 10 minutes and is not anonymous, as we will ask you to provide some personal information (name, age, education, gender etc). However, all responses are treated as confidential. If you have any questions, please feel free to ask one of the researchers before you to decide whether to begin.</p><p>By ticking the box below, you confirm that you are at least 18 years and consent to the use your results as part of our attention study. </p></body></html>"))
        self.lblError0.setText(_translate("MainWindow", "Please agree to the T&Cs if you wish to proceed"))
        self.lblConsent.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Consent</span></p></body></html>"))
        self.btnConfirm.setText(_translate("MainWindow", "Confirm"))
        self.btnSubmit.setText(_translate("MainWindow", "Submit"))
        self.lblDemographics.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Demographics</span></p></body></html>"))
        self.lblErrorEmail.setText(_translate("MainWindow", "Please enter your email"))
        self.lblPlease.setText(_translate("MainWindow", "Please provide the following information:"))
        self.lblEmail.setText(_translate("MainWindow", "Email"))
        self.cbEducation.setItemText(0, _translate("MainWindow", "Please select"))
        self.cbEducation.setItemText(1, _translate("MainWindow", "No formal education"))
        self.cbEducation.setItemText(2, _translate("MainWindow", "High school"))
        self.cbEducation.setItemText(3, _translate("MainWindow", "Vocational training"))
        self.cbEducation.setItemText(4, _translate("MainWindow", "University"))
        self.cbEducation.setItemText(5, _translate("MainWindow", "Masters"))
        self.cbEducation.setItemText(6, _translate("MainWindow", "PhD"))
        self.lblErrorGender.setText(_translate("MainWindow", "Please indicate your gender"))
        self.lblAge.setText(_translate("MainWindow", "Age*"))
        self.lblEducation.setText(_translate("MainWindow", "Education*"))
        self.rbtnWoman.setText(_translate("MainWindow", "Female"))
        self.rbtnMan.setText(_translate("MainWindow", "Male"))
        self.rbtnOther.setText(_translate("MainWindow", "Other"))
        self.lblName.setText(_translate("MainWindow", "Name*"))
        self.lblErrorAge.setText(_translate("MainWindow", "Please input your age"))
        self.lblErrorEduc.setText(_translate("MainWindow", "Please select your education level"))
        self.lblErrorName.setText(_translate("MainWindow", "Please write your name"))
        self.lblGender.setText(_translate("MainWindow", "Gender"))
        self.lblInstructions.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Instructions</span></p></body></html>"))
        self.lblDescription.setText(_translate("MainWindow", "<html><head/><body><p>You will be shown 30 consecutive frames with 7 elements placed in a circle around the fixation dot, as seen below:</p><p>In every trial, there will be 2 random frames which contain one number. The aim is for you to remember the numbers hidden among the alphabet letters (distractors) and input them at the end of each trial. </p><p><br/></p><p><br/></p></body></html>"))
        self.btnNext.setText(_translate("MainWindow", "Next"))
        self.lblFixPoint.setText(_translate("MainWindow", "<html><head/><body><p>+</p></body></html>"))
        self.lblPractice2.setText(_translate("MainWindow", "This is a Practice trial"))
        self.lblQuestion.setText(_translate("MainWindow", "Which two target digits appeared in the previous trial? Please enter T1 and T2 in order. If you are not sure, you can guess, but if you don\'t want to guess than please press 0"))
        self.lblEntry1.setText(_translate("MainWindow", "Digit 1"))
        self.lblEntry2.setText(_translate("MainWindow", "Digit 2"))
        self.lblAnswer1.setText(_translate("MainWindow", "Answer 1:"))
        self.lblAnswer2.setText(_translate("MainWindow", "Answer 2:"))
        self.lblErrorDigit.setText(_translate("MainWindow", "Please enter a number"))
        self.lblPractice.setText(_translate("MainWindow", "This is a Practice trial"))
        self.lblDebrief.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Debrief</span></p></body></html>"))
        self.lblThanks.setText(_translate("MainWindow", "<html><head/><body><p>You have now completed the experiment, we thank you taking the time to participate!</p><p><br/></p><p>Have a nice day! :)</p></body></html>"))

